# Missing Values

In [6]:
import numpy as np
import pandas as pd

## Work With Missig Values

In [14]:
import pandas as pd
import numpy as np
from numpy import nan as NA

data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], 
                     [NA, NA, NA], [NA, 6.5, 3.]])
data.index = ['A','B','C','D']
data

     0    1    2
A  1.0  6.5  3.0
B  1.0  NaN  NaN
C  NaN  NaN  NaN
D  NaN  6.5  3.0

In [15]:
data.isna()

       0      1      2
A  False  False  False
B  False   True   True
C   True   True   True
D   True  False  False

In [16]:
data.isna().sum()

0    2
1    2
2    2
dtype: int64

In [21]:
data.dropna()

     0    1    2    3    4
A  1.0  6.5  3.0  8.0  2.3

In [18]:
data = pd.DataFrame([[1., 6.5, 3., 8., 2.3], [1., NA, NA, 5, 1.4],
                     [NA, NA, 2,  NA, 4.5], [NA, 6.5, 3.,NA, 3.1],
                     [2.5, 8.1, NA, NA, 2], [NA , NA, NA , 4.2, NA],
                     [2, 5.2, 1.8, NA, 2.5]])
data.index = ['A','B','C','D','E','F','G']
data

     0    1    2    3    4
A  1.0  6.5  3.0  8.0  2.3
B  1.0  NaN  NaN  5.0  1.4
C  NaN  NaN  2.0  NaN  4.5
D  NaN  6.5  3.0  NaN  3.1
E  2.5  8.1  NaN  NaN  2.0
F  NaN  NaN  NaN  4.2  NaN
G  2.0  5.2  1.8  NaN  2.5

In [19]:
data.dropna(thresh=3)

     0    1    2    3    4
A  1.0  6.5  3.0  8.0  2.3
B  1.0  NaN  NaN  5.0  1.4
D  NaN  6.5  3.0  NaN  3.1
E  2.5  8.1  NaN  NaN  2.0
G  2.0  5.2  1.8  NaN  2.5

In [7]:
df = pd.read_csv("weather.csv")
df

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),rain (mm),showers (mm),snowfall (cm),wind_speed_180m (km/h)
0,2024-11-03T00:00,NaN,56,3.8,0.0,0.0,0.0,6.0
1,2024-11-03T01:00,12.4,57,4.1,0.0,0.0,0.0,7.0
2,2024-11-03T02:00,12.4,58,4.3,0.0,0.0,0.0,9.2
3,2024-11-03T03:00,12.7,55,3.9,0.0,0.0,0.0,12.7
4,2024-11-03T04:00,13.8,52,4.1,0.0,0.0,0.0,12.1
...,...,...,...,...,...,...,...,...
163,2024-11-09T19:00,6.7,70,1.6,0.0,0.0,0.0,2.6
164,2024-11-09T20:00,6.4,72,1.7,0.0,0.0,0.0,2.4
165,2024-11-09T21:00,6.2,73,1.7,0.0,0.0,0.0,2.2
166,2024-11-09T22:00,6.3,71,1.4,0.0,0.0,0.0,1.8
167,2024-11-09T23:00,6.6,67,0.9,0.0,0.0,0.0,2.5

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time                      168 non-null    object
 1   temperature_2m (°C)       167 non-null    float64
 2   relative_humidity_2m (%)  168 non-null    int64
 3   dew_point_2m (°C)         168 non-null    float64
 4   rain (mm)                 168 non-null    float64
 5   showers (mm)              168 non-null    float64
 6   snowfall (cm)             168 non-null    float64
 7   wind_speed_180m (km/h)    168 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 10.6+ KB

In [9]:
df.describe()

,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),rain (mm),showers (mm),snowfall (cm),wind_speed_180m (km/h)
count,167.000000,168.000000,168.000000,168.000000,168.000000,168.0,168.000000
mean,13.383832,51.851190,2.892857,0.006548,0.009524,0.0,10.018452
std,4.047122,16.420245,4.061173,0.062041,0.038284,0.0,6.687916
min,6.200000,18.000000,-5.800000,0.000000,0.000000,0.0,0.400000
25%,9.950000,40.000000,0.675000,0.000000,0.000000,0.0,4.875000
50%,13.600000,52.000000,2.000000,0.000000,0.000000,0.0,8.900000
75%,16.400000,64.000000,6.900000,0.000000,0.000000,0.0,13.050000
max,21.700000,89.000000,10.300000,0.700000,0.300000,0.0,29.100000

In [10]:
df.dropna()

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),rain (mm),showers (mm),snowfall (cm),wind_speed_180m (km/h)
1,2024-11-03T01:00,12.4,57,4.1,0.0,0.0,0.0,7.0
2,2024-11-03T02:00,12.4,58,4.3,0.0,0.0,0.0,9.2
3,2024-11-03T03:00,12.7,55,3.9,0.0,0.0,0.0,12.7
4,2024-11-03T04:00,13.8,52,4.1,0.0,0.0,0.0,12.1
5,2024-11-03T05:00,16.5,44,4.2,0.0,0.0,0.0,9.2
...,...,...,...,...,...,...,...,...
163,2024-11-09T19:00,6.7,70,1.6,0.0,0.0,0.0,2.6
164,2024-11-09T20:00,6.4,72,1.7,0.0,0.0,0.0,2.4
165,2024-11-09T21:00,6.2,73,1.7,0.0,0.0,0.0,2.2
166,2024-11-09T22:00,6.3,71,1.4,0.0,0.0,0.0,1.8
167,2024-11-09T23:00,6.6,67,0.9,0.0,0.0,0.0,2.5

## Related to the column

In [12]:
df['temperature_2m (°C)'].mean()

np.float64(13.383832335329341)

In [13]:
df['temperature_2m (°C)'].median()

13.6

In [11]:
df.fillna(df['temperature_2m (°C)'].mean())

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),rain (mm),showers (mm),snowfall (cm),wind_speed_180m (km/h)
0,2024-11-03T00:00,13.383832,56,3.8,0.0,0.0,0.0,6.0
1,2024-11-03T01:00,12.400000,57,4.1,0.0,0.0,0.0,7.0
2,2024-11-03T02:00,12.400000,58,4.3,0.0,0.0,0.0,9.2
3,2024-11-03T03:00,12.700000,55,3.9,0.0,0.0,0.0,12.7
4,2024-11-03T04:00,13.800000,52,4.1,0.0,0.0,0.0,12.1
...,...,...,...,...,...,...,...,...
163,2024-11-09T19:00,6.700000,70,1.6,0.0,0.0,0.0,2.6
164,2024-11-09T20:00,6.400000,72,1.7,0.0,0.0,0.0,2.4
165,2024-11-09T21:00,6.200000,73,1.7,0.0,0.0,0.0,2.2
166,2024-11-09T22:00,6.300000,71,1.4,0.0,0.0,0.0,1.8
167,2024-11-09T23:00,6.600000,67,0.9,0.0,0.0,0.0,2.5

In [ ]:
data.drop(data.columns[data.isna().sum()/len(data) >= 0.8] , axis = 1)

## Related to the Rows