# Wrong Format

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('weather.csv')
df

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),rain (mm),showers (mm),snowfall (cm),wind_speed_180m (km/h)
0,2024-11-03T00:00,NaN,56,3.8,0.0,0.0,0.0,a
1,2024-11-03T01:00,12.4,57,4.1,0.0,0.0,0.0,7.0
2,2024-11-03T02:00,12.4,58,4.3,0.0,0.0,0.0,9.2
3,2024-11-03T03:00,12.7,55,3.9,0.0,0.0,0.0,12.7
4,2024-11-03T04:00,13.8,52,4.1,0.0,0.0,0.0,12.1
...,...,...,...,...,...,...,...,...
163,2024-11-09T19:00,6.7,70,1.6,0.0,0.0,0.0,2.6
164,2024-11-09T20:00,6.4,72,1.7,0.0,0.0,0.0,2.4
165,2024-11-09T21:00,6.2,73,1.7,0.0,0.0,0.0,2.2
166,2024-11-09T22:00,6.3,71,1.4,0.0,0.0,0.0,1.8
167,2024-11-09T23:00,6.6,67,0.9,0.0,0.0,0.0,2.5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time                      168 non-null    object
 1   temperature_2m (°C)       167 non-null    float64
 2   relative_humidity_2m (%)  168 non-null    int64
 3   dew_point_2m (°C)         168 non-null    float64
 4   rain (mm)                 168 non-null    float64
 5   showers (mm)              168 non-null    float64
 6   snowfall (cm)             168 non-null    float64
 7   wind_speed_180m (km/h)    168 non-null    object
dtypes: float64(5), int64(1), object(2)
memory usage: 10.6+ KB

In [4]:
# df["wind_speed_180m (km/h)"] = pd.to_numeric(df["wind_speed_180m (km/h)"], errors="raise")
# df["wind_speed_180m (km/h)"] = pd.to_numeric(df["wind_speed_180m (km/h)"], errors="ignore")
df["wind_speed_180m (km/h)"] = pd.to_numeric(df["wind_speed_180m (km/h)"], errors="coerce", downcast="float")

In [5]:
df

,time,temperature_2m (°C),relative_humidity_2m (%),dew_point_2m (°C),rain (mm),showers (mm),snowfall (cm),wind_speed_180m (km/h)
0,2024-11-03T00:00,NaN,56,3.8,0.0,0.0,0.0,NaN
1,2024-11-03T01:00,12.4,57,4.1,0.0,0.0,0.0,7.0
2,2024-11-03T02:00,12.4,58,4.3,0.0,0.0,0.0,9.2
3,2024-11-03T03:00,12.7,55,3.9,0.0,0.0,0.0,12.7
4,2024-11-03T04:00,13.8,52,4.1,0.0,0.0,0.0,12.1
...,...,...,...,...,...,...,...,...
163,2024-11-09T19:00,6.7,70,1.6,0.0,0.0,0.0,2.6
164,2024-11-09T20:00,6.4,72,1.7,0.0,0.0,0.0,2.4
165,2024-11-09T21:00,6.2,73,1.7,0.0,0.0,0.0,2.2
166,2024-11-09T22:00,6.3,71,1.4,0.0,0.0,0.0,1.8
167,2024-11-09T23:00,6.6,67,0.9,0.0,0.0,0.0,2.5