# Pandas

In [51]:
import pandas as pd
import numpy as np
from matplotlib.pyplot import axis

## Pandas Methods

### Create Series

In [2]:
labels = ['a', 'b', 'c']
array = np.array([1, 2, 3])
series = pd.Series(array, labels)
series

a    1
b    2
c    3
dtype: int64

In [3]:
print(type(series))

<class 'pandas.core.series.Series'>

In [4]:
series = pd.Series(data = array, index = labels)
series

a    1
b    2
c    3
dtype: int64

In [5]:
series = pd.Series(data = [1, 2, 3, 4], index = ["Iran", "Canada", "Germany", "France"])
series

Iran       1
Canada     2
Germany    3
France     4
dtype: int64

In [6]:
series.shape

(4,)

In [7]:
series.iloc[0]

np.int64(1)

In [8]:
series["Iran"]

np.int64(1)

### Create DataFrame & Modify

In [9]:
data = {
    "name": ["Ali", "Ahmad", "Sina"],
    "age": [20, 26, 21],
    "city": ["Tehran", "Shiraz", "Qom"]
}
rand_df = pd.DataFrame(data)
rand_df

    name  age    city
0    Ali   20  Tehran
1  Ahmad   26  Shiraz
2   Sina   21     Qom

In [10]:
data = [
    ["Ali", "Ahmad", "Sina"],
    [20, 26, 21],
    ["Tehran", "Shiraz", "Qom"]
]
rand_df2 = pd.DataFrame(data, columns=["name", "age", "city"])
rand_df2

     name     age  city
0     Ali   Ahmad  Sina
1      20      26    21
2  Tehran  Shiraz   Qom

In [11]:
data = [
    {'name': 'Ali', 'age': 22},
    {'name': 'Sara', 'age': 25},
    {'name': 'Reza', 'age': 30}
]

df = pd.DataFrame(data)
print(df)

   name  age
0   Ali   22
1  Sara   25
2  Reza   30

In [12]:
rand_df3 = pd.DataFrame(data=np.random.rand(5, 4),
                  index=[1, 2, 3, 4, 5],
                  columns=["Age", "Salary", "Talent", "Tax"])
rand_df3

        Age    Salary    Talent       Tax
1  0.874101  0.026140  0.404082  0.804992
2  0.336999  0.519117  0.398149  0.900015
3  0.060673  0.083538  0.575981  0.384749
4  0.731358  0.235843  0.320818  0.385456
5  0.511678  0.918371  0.065497  0.273181

In [13]:
df = pd.DataFrame(
    data = {
        "age": [14, 24, 26, 56, 46, 55, 59],
        "salary": [100, 200, 300, 400, 500, 600, 700],
    },
    index=["ali", "Ahmad", "Sara", "Reza", "Vahid", "Soheil", "Hossein"]
)
df

         age  salary
ali       14     100
Ahmad     24     200
Sara      26     300
Reza      56     400
Vahid     46     500
Soheil    55     600
Hossein   59     700

#### Add a column

In [14]:
rand_df3['New'] = rand_df3["Age"] + rand_df3["Salary"]
rand_df3

        Age    Salary    Talent       Tax       New
1  0.874101  0.026140  0.404082  0.804992  0.900242
2  0.336999  0.519117  0.398149  0.900015  0.856116
3  0.060673  0.083538  0.575981  0.384749  0.144211
4  0.731358  0.235843  0.320818  0.385456  0.967202
5  0.511678  0.918371  0.065497  0.273181  1.430048

In [15]:
rand_df3["New 2"] = np.random.randint(5, 10, 5)
rand_df3

        Age    Salary    Talent       Tax       New  New 2
1  0.874101  0.026140  0.404082  0.804992  0.900242      6
2  0.336999  0.519117  0.398149  0.900015  0.856116      9
3  0.060673  0.083538  0.575981  0.384749  0.144211      6
4  0.731358  0.235843  0.320818  0.385456  0.967202      6
5  0.511678  0.918371  0.065497  0.273181  1.430048      9

#### Add a row

In [16]:
rand_df3.loc["NewRow"] = [100, 200, 300, 400, 500, 600]
rand_df3

               Age      Salary      Talent         Tax         New  New 2
1         0.874101    0.026140    0.404082    0.804992    0.900242      6
2         0.336999    0.519117    0.398149    0.900015    0.856116      9
3         0.060673    0.083538    0.575981    0.384749    0.144211      6
4         0.731358    0.235843    0.320818    0.385456    0.967202      6
5         0.511678    0.918371    0.065497    0.273181    1.430048      9
NewRow  100.000000  200.000000  300.000000  400.000000  500.000000    600

### Open DataFrame

In [17]:
df1 = pd.read_csv("file.csv")
print(type(df1))
df1

<class 'pandas.core.frame.DataFrame'>

     name  math  geo
0   Ahmad    20   18
1    Sina    14   20
2  Mahyar    20   11
3  Farbod    17   13
4   Akbar    19   16

In [18]:
df2 = pd.read_json("file.json")
print(type(df2))
df2

<class 'pandas.core.frame.DataFrame'>

    name  math  jeo
0   JSON    20   16
1  Ahmad    17   12

In [19]:
df3 = pd.read_xml("file.xml")
print(type(df3))
df3

<class 'pandas.core.frame.DataFrame'>

    name  math  geo
0    XML    20   16
1  Ahmad    11   20

## Pandas Attribute

### Convert DataFrame

In [20]:
df3.to_csv("converted.csv", index=False)

In [21]:
df3.to_excel("converted.xlsx", index=False)

In [22]:
df3.to_json("converted.json", index=False)

### info, describe

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   math    5 non-null      int64
 2   geo     5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes

In [24]:
df1.describe()

           math        geo
count   5.00000   5.000000
mean   18.00000  15.600000
std     2.54951   3.646917
min    14.00000  11.000000
25%    17.00000  13.000000
50%    19.00000  16.000000
75%    20.00000  18.000000
max    20.00000  20.000000

In [25]:
mean = df1["math"].mean()
mean

np.float64(18.0)

In [26]:
mean = np.mean(df1["math"].values)
mean

np.float64(18.0)

In [27]:
df1.to_csv("converted.csv", index=False)

In [28]:
df3.to_excel("converted.xlsx", index=False)

In [29]:
df3.to_json("converted.json", index=False)

### Drop

In [30]:
rand_df3

               Age      Salary      Talent         Tax         New  New 2
1         0.874101    0.026140    0.404082    0.804992    0.900242      6
2         0.336999    0.519117    0.398149    0.900015    0.856116      9
3         0.060673    0.083538    0.575981    0.384749    0.144211      6
4         0.731358    0.235843    0.320818    0.385456    0.967202      6
5         0.511678    0.918371    0.065497    0.273181    1.430048      9
NewRow  100.000000  200.000000  300.000000  400.000000  500.000000    600

In [31]:
rand_df3.drop('New 2', axis=1)

               Age      Salary      Talent         Tax         New
1         0.874101    0.026140    0.404082    0.804992    0.900242
2         0.336999    0.519117    0.398149    0.900015    0.856116
3         0.060673    0.083538    0.575981    0.384749    0.144211
4         0.731358    0.235843    0.320818    0.385456    0.967202
5         0.511678    0.918371    0.065497    0.273181    1.430048
NewRow  100.000000  200.000000  300.000000  400.000000  500.000000

In [32]:
rand_df3

               Age      Salary      Talent         Tax         New  New 2
1         0.874101    0.026140    0.404082    0.804992    0.900242      6
2         0.336999    0.519117    0.398149    0.900015    0.856116      9
3         0.060673    0.083538    0.575981    0.384749    0.144211      6
4         0.731358    0.235843    0.320818    0.385456    0.967202      6
5         0.511678    0.918371    0.065497    0.273181    1.430048      9
NewRow  100.000000  200.000000  300.000000  400.000000  500.000000    600

In [33]:
rand_df3.drop("New 2", axis=1, inplace=True)

In [34]:
rand_df3

               Age      Salary      Talent         Tax         New
1         0.874101    0.026140    0.404082    0.804992    0.900242
2         0.336999    0.519117    0.398149    0.900015    0.856116
3         0.060673    0.083538    0.575981    0.384749    0.144211
4         0.731358    0.235843    0.320818    0.385456    0.967202
5         0.511678    0.918371    0.065497    0.273181    1.430048
NewRow  100.000000  200.000000  300.000000  400.000000  500.000000

In [35]:
rand_df3.drop("NewRow", axis=0)

        Age    Salary    Talent       Tax       New
1  0.874101  0.026140  0.404082  0.804992  0.900242
2  0.336999  0.519117  0.398149  0.900015  0.856116
3  0.060673  0.083538  0.575981  0.384749  0.144211
4  0.731358  0.235843  0.320818  0.385456  0.967202
5  0.511678  0.918371  0.065497  0.273181  1.430048

### reset_index

In [36]:
df.reset_index()

     index  age  salary
0      ali   14     100
1    Ahmad   24     200
2     Sara   26     300
3     Reza   56     400
4    Vahid   46     500
5   Soheil   55     600
6  Hossein   59     700

### set_index

In [37]:
columns = [["Tehran", "Esfahan", "Shirza", "Mashhad", "Qom", "Karaj", "Gilan"]]

In [38]:
df.set_index(columns)

         age  salary
Tehran    14     100
Esfahan   24     200
Shirza    26     300
Mashhad   56     400
Qom       46     500
Karaj     55     600
Gilan     59     700

### Rename Columns

In [39]:
df.columns = [["Surface", "Perimeter"]]

In [40]:
df

        Surface Perimeter
ali          14       100
Ahmad        24       200
Sara         26       300
Reza         56       400
Vahid        46       500
Soheil       55       600
Hossein      59       700

## Indexing & slicing

### Column Access

In [41]:
df1

     name  math  geo
0   Ahmad    20   18
1    Sina    14   20
2  Mahyar    20   11
3  Farbod    17   13
4   Akbar    19   16

In [42]:
df1["math"]

0    20
1    14
2    20
3    17
4    19
Name: math, dtype: int64

In [43]:
df1.math

0    20
1    14
2    20
3    17
4    19
Name: math, dtype: int64

In [44]:
df1[["math", "geo", "name"]]

   math  geo    name
0    20   18   Ahmad
1    14   20    Sina
2    20   11  Mahyar
3    17   13  Farbod
4    19   16   Akbar

### Row Access

In [45]:
df.iloc[0]

Surface       14
Perimeter    100
Name: ali, dtype: int64

In [46]:
df.iloc[1]

Surface       24
Perimeter    200
Name: Ahmad, dtype: int64

In [47]:
new_df = pd.DataFrame(data=np.random.rand(5, 4),
                      index=["a", "b", "c", "d", "c"],
                      columns=["math", "geo", "salary", "tax"])
new_df

       math       geo    salary       tax
a  0.676115  0.659201  0.185487  0.778711
b  0.781964  0.305054  0.835118  0.347279
c  0.564001  0.760493  0.247467  0.258650
d  0.896643  0.440213  0.819469  0.448630
c  0.740408  0.997452  0.204736  0.322624

In [48]:
new_df.loc["a"]

math      0.676115
geo       0.659201
salary    0.185487
tax       0.778711
Name: a, dtype: float64

In [49]:
new_df.iloc[0]

math      0.676115
geo       0.659201
salary    0.185487
tax       0.778711
Name: a, dtype: float64

### Row & Column Access

In [50]:
df[["name", "math"]].iloc[0]

KeyError: "['name' 'math'] not in index"

In [ ]:
df[["name", "math"]].iloc[1]

In [ ]:
df

In [ ]:
df.iloc[[1, 2]][["Age", "Salary"]]

### Conditional Selecting

In [ ]:
df > 10

In [ ]:
df < 5

In [ ]:
df[df>50]

In [ ]:
df[df["age"] > 50]

In [ ]:
df[df["age"] > 50]["salary"]