# Pandas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame(
    data={
        "Age": [26, 28, 30, 40, 50, 10, 23, 24, 25, 27],
        "Math": [20, 13, 14, 15, 16, 20, 19, 18, 17, 15],
        "Geo": [20, 20, 18, 19, 17, 18.5, 19.5, 20, 16, 15]
    },
    index=["Ahmad", "Farid", "Vahid", "Mohammad", "Abbas", "Shayan", "Soheil", "Mehran", "Farbod", "Hossein"]
)

In [3]:
df

          Age  Math   Geo
Ahmad      26    20  20.0
Farid      28    13  20.0
Vahid      30    14  18.0
Mohammad   40    15  19.0
Abbas      50    16  17.0
Shayan     10    20  18.5
Soheil     23    19  19.5
Mehran     24    18  20.0
Farbod     25    17  16.0
Hossein    27    15  15.0

### Create New column

In [4]:
df["Mean"] = (df["Math"] + df["Geo"]) / 2

In [5]:
df

          Age  Math   Geo   Mean
Ahmad      26    20  20.0  20.00
Farid      28    13  20.0  16.50
Vahid      30    14  18.0  16.00
Mohammad   40    15  19.0  17.00
Abbas      50    16  17.0  16.50
Shayan     10    20  18.5  19.25
Soheil     23    19  19.5  19.25
Mehran     24    18  20.0  19.00
Farbod     25    17  16.0  16.50
Hossein    27    15  15.0  15.00

In [6]:
df["Salary"] = np.random.randint(1_000, 3_000, 10)

In [7]:
df

          Age  Math   Geo   Mean  Salary
Ahmad      26    20  20.0  20.00    2003
Farid      28    13  20.0  16.50    2497
Vahid      30    14  18.0  16.00    2904
Mohammad   40    15  19.0  17.00    1091
Abbas      50    16  17.0  16.50    2666
Shayan     10    20  18.5  19.25    2413
Soheil     23    19  19.5  19.25    2909
Mehran     24    18  20.0  19.00    1771
Farbod     25    17  16.0  16.50    2526
Hossein    27    15  15.0  15.00    2764

### Create New Row

In [10]:
df.loc["Ali"] = [30, 5, 10, 7.5, 100]

In [11]:
df

           Age  Math   Geo   Mean  Salary
Ahmad     26.0  20.0  20.0  20.00  2003.0
Farid     28.0  13.0  20.0  16.50  2497.0
Vahid     30.0  14.0  18.0  16.00  2904.0
Mohammad  40.0  15.0  19.0  17.00  1091.0
Abbas     50.0  16.0  17.0  16.50  2666.0
Shayan    10.0  20.0  18.5  19.25  2413.0
Soheil    23.0  19.0  19.5  19.25  2909.0
Mehran    24.0  18.0  20.0  19.00  1771.0
Farbod    25.0  17.0  16.0  16.50  2526.0
Hossein   27.0  15.0  15.0  15.00  2764.0
Ali       30.0   5.0  10.0   7.50   100.0

## Pandas Attribute

### Convert DataFrame

In [13]:
df.to_csv("Persons.csv", index=False)

In [17]:
df.to_excel("Persons.xlsx", index=False)

In [18]:
df.to_json("converted.json", index=False)

### info, describe

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, Ahmad to Ali
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     11 non-null     float64
 1   Math    11 non-null     float64
 2   Geo     11 non-null     float64
 3   Mean    11 non-null     float64
 4   Salary  11 non-null     float64
dtypes: float64(5)
memory usage: 828.0+ bytes

In [20]:
df.describe()

             Age       Math        Geo       Mean       Salary
count  11.000000  11.000000  11.000000  11.000000    11.000000
mean   28.454545  15.636364  17.545455  16.590909  2149.454545
std    10.063435   4.249064   3.020385   3.424676   872.240261
min    10.000000   5.000000  10.000000   7.500000   100.000000
25%    24.500000  14.500000  16.500000  16.250000  1887.000000
50%    27.000000  16.000000  18.500000  16.500000  2497.000000
75%    30.000000  18.500000  19.750000  19.125000  2715.000000
max    50.000000  20.000000  20.000000  20.000000  2909.000000

### Drop

In [21]:
df

           Age  Math   Geo   Mean  Salary
Ahmad     26.0  20.0  20.0  20.00  2003.0
Farid     28.0  13.0  20.0  16.50  2497.0
Vahid     30.0  14.0  18.0  16.00  2904.0
Mohammad  40.0  15.0  19.0  17.00  1091.0
Abbas     50.0  16.0  17.0  16.50  2666.0
Shayan    10.0  20.0  18.5  19.25  2413.0
Soheil    23.0  19.0  19.5  19.25  2909.0
Mehran    24.0  18.0  20.0  19.00  1771.0
Farbod    25.0  17.0  16.0  16.50  2526.0
Hossein   27.0  15.0  15.0  15.00  2764.0
Ali       30.0   5.0  10.0   7.50   100.0

In [22]:
df.drop("Salary", axis=1)
# df.drop("Salary", axis=1, inplace=True)

           Age  Math   Geo   Mean
Ahmad     26.0  20.0  20.0  20.00
Farid     28.0  13.0  20.0  16.50
Vahid     30.0  14.0  18.0  16.00
Mohammad  40.0  15.0  19.0  17.00
Abbas     50.0  16.0  17.0  16.50
Shayan    10.0  20.0  18.5  19.25
Soheil    23.0  19.0  19.5  19.25
Mehran    24.0  18.0  20.0  19.00
Farbod    25.0  17.0  16.0  16.50
Hossein   27.0  15.0  15.0  15.00
Ali       30.0   5.0  10.0   7.50

In [26]:
df.drop("Ali", axis=0)
# df.drop("Ali", axis=0, inplace=True)

           Age  Math   Geo   Mean  Salary
Ahmad     26.0  20.0  20.0  20.00  2003.0
Farid     28.0  13.0  20.0  16.50  2497.0
Vahid     30.0  14.0  18.0  16.00  2904.0
Mohammad  40.0  15.0  19.0  17.00  1091.0
Abbas     50.0  16.0  17.0  16.50  2666.0
Shayan    10.0  20.0  18.5  19.25  2413.0
Soheil    23.0  19.0  19.5  19.25  2909.0
Mehran    24.0  18.0  20.0  19.00  1771.0
Farbod    25.0  17.0  16.0  16.50  2526.0
Hossein   27.0  15.0  15.0  15.00  2764.0

### Reset_index

In [29]:
df2 = pd.DataFrame(data=np.random.rand(6, 4), columns=["Age", "Math", "Geo", "Salary"])

In [31]:
df2

        Age      Math       Geo    Salary
0  0.644545  0.619264  0.918567  0.051734
1  0.327566  0.019389  0.644963  0.808557
2  0.076546  0.827960  0.936408  0.672902
3  0.076410  0.836050  0.331356  0.487064
4  0.042117  0.847689  0.185942  0.932848
5  0.872323  0.200373  0.930347  0.267130

In [33]:
df2.drop(2, axis=0, inplace=True)

In [34]:
df2

        Age      Math       Geo    Salary
0  0.644545  0.619264  0.918567  0.051734
1  0.327566  0.019389  0.644963  0.808557
3  0.076410  0.836050  0.331356  0.487064
4  0.042117  0.847689  0.185942  0.932848
5  0.872323  0.200373  0.930347  0.267130

In [35]:
df2.reset_index()
# df2.reset_index(inplace=True)

   index       Age      Math       Geo    Salary
0      0  0.644545  0.619264  0.918567  0.051734
1      1  0.327566  0.019389  0.644963  0.808557
2      3  0.076410  0.836050  0.331356  0.487064
3      4  0.042117  0.847689  0.185942  0.932848
4      5  0.872323  0.200373  0.930347  0.267130

### Set index

In [ ]:
df2.index = ["Ali", "Abbas", "hamid", "mohsen"]