# Pandas Functions

In [1]:
import pandas as pd

## Merge

### Same Columns

In [28]:
cars_dictionary = {
    "model" :["Peykan", "Peykan", "Peykan", "BMW X6", "BMW X6", "Nissan Junior", "Nissan Junior", "Nissan Junior", "Nissan Junior"],
    "Color" :["Red", "White", "Olive",  "Black", "Ametrine", "Blue", "White", "Blue", "Red"],
    "HP" :[48, 48, 48, 335, 335, 93, 93, 93, 93],
    "Weight (KG)" :[990, 990, 990, 2320, 2320, 1540, 1540, 1540, 1540],
    "year" :[1346, 1357, 1388, 1391, 1393, 1375, 1383, 1375, 1389]
}

cars_df = pd.DataFrame(cars_dictionary,
                      index = [14234, 44234, 22312, 42348, 16373, 38561, 58193, 85612, 62471])
cars_df

               model     Color   HP  Weight (KG)  year
14234         Peykan       Red   48          990  1346
44234         Peykan     White   48          990  1357
22312         Peykan     Olive   48          990  1388
42348         BMW X6     Black  335         2320  1391
16373         BMW X6  Ametrine  335         2320  1393
38561  Nissan Junior      Blue   93         1540  1375
58193  Nissan Junior     White   93         1540  1383
85612  Nissan Junior      Blue   93         1540  1375
62471  Nissan Junior       Red   93         1540  1389

In [42]:
price_dictionary = {
    "model" : ["Peykan", "BMW X6", "Nissan Junior"],
    "price" : [40, 5200, 150]
}
price_df = pd.DataFrame(price_dictionary)
price_df

           model  price
0         Peykan     40
1         BMW X6   5200
2  Nissan Junior    150

In [45]:
df = pd.merge(cars_df, price_df, on='model')
df

           model     Color   HP  Weight (KG)  year  price
0         Peykan       Red   48          990  1346     40
1         Peykan     White   48          990  1357     40
2         Peykan     Olive   48          990  1388     40
3         BMW X6     Black  335         2320  1391   5200
4         BMW X6  Ametrine  335         2320  1393   5200
5  Nissan Junior      Blue   93         1540  1375    150
6  Nissan Junior     White   93         1540  1383    150
7  Nissan Junior      Blue   93         1540  1375    150
8  Nissan Junior       Red   93         1540  1389    150

### Different Columns

In [31]:
cars_dictionary = {
    "model" :["Peykan", "Peykan", "Peykan", "BMW X6", "BMW X6", "Nissan Junior", "Nissan Junior", "Nissan Junior", "Nissan Junior"],
    "Color" :["Red", "White", "Olive",  "Black", "Ametrine", "Blue", "White", "Blue", "Red"],
    "HP" :[48, 48, 48, 335, 335, 93, 93, 93, 93],
    "Weight (KG)" :[990, 990, 990, 2320, 2320, 1540, 1540, 1540, 1540],
    "year" :[1346, 1357, 1388, 1391, 1393, 1375, 1383, 1375, 1389]
}

cars_df = pd.DataFrame(cars_dictionary,
                      index = [14234, 44234, 22312, 42348, 16373, 38561, 58193, 85612, 62471])
cars_df

               model     Color   HP  Weight (KG)  year
14234         Peykan       Red   48          990  1346
44234         Peykan     White   48          990  1357
22312         Peykan     Olive   48          990  1388
42348         BMW X6     Black  335         2320  1391
16373         BMW X6  Ametrine  335         2320  1393
38561  Nissan Junior      Blue   93         1540  1375
58193  Nissan Junior     White   93         1540  1383
85612  Nissan Junior      Blue   93         1540  1375
62471  Nissan Junior       Red   93         1540  1389

In [34]:
price_dictionary2 = {
    "car model" : ["Peykan", "BMW X6", "Nissan Junior"],
    "price" : [40, 5200, 150]
}
price_df2 = pd.DataFrame(price_dictionary2)
price_df2

       car model  price
0         Peykan     40
1         BMW X6   5200
2  Nissan Junior    150

In [37]:
df = pd.merge(cars_df, price_df2, left_on='model', right_on='car model')

In [38]:
df.drop(columns=['car model'], inplace=True)

### Multiple Columns

In [39]:
cars_dictionary = {
    "model" :["Peykan", "Peykan", "Peykan", "BMW X6", "BMW X6", "Nissan Junior", "Nissan Junior", "Nissan Junior", "Nissan Junior"],
    "Color" :["Red", "White", "Olive",  "Black", "Ametrine", "Blue", "White", "Blue", "Red"],
    "HP" :[48, 48, 48, 335, 335, 93, 93, 93, 93],
    "Weight (KG)" :[990, 990, 990, 2320, 2320, 1540, 1540, 1540, 1540],
    "year" :[1346, 1357, 1388, 1391, 1393, 1375, 1383, 1375, 1389]
}

cars_df = pd.DataFrame(cars_dictionary,
                      index = [14234, 44234, 22312, 42348, 16373, 38561, 58193, 85612, 62471])
cars_df

               model     Color   HP  Weight (KG)  year
14234         Peykan       Red   48          990  1346
44234         Peykan     White   48          990  1357
22312         Peykan     Olive   48          990  1388
42348         BMW X6     Black  335         2320  1391
16373         BMW X6  Ametrine  335         2320  1393
38561  Nissan Junior      Blue   93         1540  1375
58193  Nissan Junior     White   93         1540  1383
85612  Nissan Junior      Blue   93         1540  1375
62471  Nissan Junior       Red   93         1540  1389

In [ ]:
price_with_year_dictionary = {
    "year" :[1346, 1357, 1388, 1391, 1393,  1375, 1383, 1389],
    "car model" :["Peykan", "Peykan", "Peykan", "BMW X6", "BMW X6", "Nissan Junior", "Nissan Junior", "Nissan Junior"],
    "price" :[25, 30, 48, 2200, 4800, 105, 130, 155]
}

price_with_year_df = pd.DataFrame(price_with_year_dictionary)
price_with_year_df

In [41]:
df = pd.merge(cars_df, price_with_year_df, left_on=['year', 'model'], right_on=['year', 'car model'])

### Practice 1

In [7]:
tp1 = pd.DataFrame(
    data={
        "id": [1, 2],
        'name': ['Ahmad', 'Ali']
    }
)
tp1

   id   name
0   1  Ahmad
1   2    Ali

In [8]:
tp11 = pd.DataFrame(
    data={
        "id": [1, 2],
        'score': [20, 18]
    }
)
tp11

   id  score
0   1     20
1   2     18

In [9]:
merged1 = pd.merge(tp1, tp11, on='id')
merged1

   id   name  score
0   1  Ahmad     20
1   2    Ali     18

### Practice 2

In [11]:
tp2 = pd.DataFrame(
    data={
        "student_id": [1, 2],
        'name': ['Ahmad', 'Ali']
    }
)
tp2

   student_id   name
0           1  Ahmad
1           2    Ali

In [12]:
tp22 = pd.DataFrame(
    data={
        "id": [1, 2],
        'score': [19, 20]
    }
)
tp2

   student_id   name
0           1  Ahmad
1           2    Ali

In [13]:
merged2 = pd.merge(tp2, tp22, left_on='student_id', right_on='id')

In [14]:
merged2

   student_id   name  id  score
0           1  Ahmad   1     19
1           2    Ali   2     20

### Practice 3

In [24]:
author = pd.DataFrame(
    data={
        "Author": ["Rowling", "Tolkien"]
    }
)
author

    Author
0  Rowling
1  Tolkien

In [27]:
books = pd.DataFrame(
    data={
        "authors_id": [1, 2],
        "title": ["HP", "Hobbits"]
    },

)
books

   authors_id    title
0           1       HP
1           2  Hobbits

In [21]:
merged3 = pd.merge()
merged3

    Author    title
0  Rowling       HP
1  Tolkien  Hobbits