In [2]:
import pandas as pd

# 1

In [3]:
students = {
    'name': ['Ahmad', 'Ariana', 'Vahid'],
    'student_id': [1, 2, 3]
}
students_df = pd.DataFrame(data=students)
students_df

     name  student_id
0   Ahmad           1
1  Ariana           2
2   Vahid           3

In [5]:
scores = {
    "score": [18, 20, 17],
    'student_id': [1, 2, 3]
}
scores_df = pd.DataFrame(data=scores)
scores_df

   score  student_id
0     18           1
1     20           2
2     17           3

In [8]:
pd.merge(students_df, scores_df, on="student_id")

     name  student_id  score
0   Ahmad           1     18
1  Ariana           2     20
2   Vahid           3     17

# 2

In [10]:
students2 = {
    'name': ['Ahmad', 'Ariana', 'Vahid', 'Peyman'],
    'student_id': [1, 2, 3, 4]
}
students_df2 = pd.DataFrame(data=students2)
students_df2

     name  student_id
0   Ahmad           1
1  Ariana           2
2   Vahid           3
3  Peyman           4

In [11]:
scores2 = {
    "score": [18, 20, 17, 15],
    'id': [1, 2, 3, 4]
}
scores_df2 = pd.DataFrame(data=scores2)
scores_df2

   score  id
0     18   1
1     20   2
2     17   3
3     15   4

In [12]:
pd.merge(students_df2, scores_df2, left_on="student_id", right_on='id')

     name  student_id  score  id
0   Ahmad           1     18   1
1  Ariana           2     20   2
2   Vahid           3     17   3
3  Peyman           4     15   4

# 3

In [13]:
books = {
    'title': ['HP', 'Hobbit'],
    'authors_id': [0, 1]
}
book_df = pd.DataFrame(books)
book_df

    title  authors_id
0      HP           0
1  Hobbit           1

In [15]:
authors = {
    'author': ["Rowing", "Tolkien"]
}
authors_df = pd.DataFrame(authors)
authors_df

    author
0   Rowing
1  Tolkien

In [16]:
pd.merge(book_df, authors_df, left_on='authors_id', right_index=True)

    title  authors_id   author
0      HP           0   Rowing
1  Hobbit           1  Tolkien