<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h2 style="color:#306998; font-size:23px; font-weight:700; border-bottom:1px solid #EAF2F8; padding-bottom:10px; margin:0 0 18px;">📖 انتخاب ستون‌ها</h2>
<p style="margin:0 0 14px; text-align:justify;">در Part I یاد گرفتیم DataFrame چیست، چگونه ساخته یا خوانده می‌شود، و با ابزارهای کاوش (مثل <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">columns</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">head()</code>) ساختار کلی آن را می‌شناسیم. حالا قدم بعدی، <strong>انتخاب بخشی از داده</strong> است — اولین و ساده‌ترین حالت: انتخاب ستون.</p>
<div style="background:#EAF2F8; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:18px 0; text-align:right; font-weight:600; font-size:18px; color:#306998;">انتخاب ستون = حرکت روی محور axis=1؛ یعنی از بین نام ستون‌ها، یک یا چند ستون را برمی‌داریم.</div>
<div style="background:#F8F9FB; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:0 0 26px;">
    <div style="font-weight:700; color:#306998; margin-bottom:6px;">🧠 مدل ذهنی</div>
    <p style="margin:0; text-align:right;">یک ستون --> خروجی <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code> (یک‌بعدی). چند ستون --> خروجی <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code> کوچک‌تر (دو‌بعدی). این تفاوت در ادامه‌ی همین فصل بارها تکرار می‌شود.</p>
  </div>
<hr style="border:none; border-top:1px solid #E6E9ED; margin:22px 0;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">📌 انتخاب یک ستون</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">سینتکس اصلی: براکت تکی</p>
<p style="margin:0 0 14px; text-align:justify;">رایج‌ترین روش، استفاده از یک براکت و نام ستون به‌صورت رشته است: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["model"]</code>. خروجی یک <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code> است؛ index آن همان برچسب ردیف‌های DataFrame است و values آن، مقادیر آن ستون.</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نوع</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["model"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ستون</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["HP"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ستون عددی</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td></tr></tbody>
  </table>
<p style="margin:10px 0 4px; text-align:justify;">همان DataFrame خودروها را بسازید. ستون <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"model"</code> را انتخاب کنید و با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">type()</code> نوع خروجی را بررسی کنید.</p>
  <!-- کد را خودت بنویس -->
</div>

In [2]:
import pandas as pd
cars_dictionary = {
    "model" :[ "Peykan", "BMW X6", "Peugeot 206", "Tiba", "Nissan Junior", "Peykan Vanet", "renault 5"],
    "Color" :["Red", "White", "Black", "White", "Blue", "Red", "Silver"],
    "HP" :[48, 335, 105, 87, 93, 80, 48],
    "Weight (KG)": [990, 2320, 1025, 1027, 1540, 960, 850],
    "price" :[33, 2400, 105, 120, 230, 68, 38]
}

df = pd.DataFrame(cars_dictionary)
df

           model   Color   HP  Weight (KG)  price
0         Peykan     Red   48          990     33
1         BMW X6   White  335         2320   2400
2    Peugeot 206   Black  105         1025    105
3           Tiba   White   87         1027    120
4  Nissan Junior    Blue   93         1540    230
5   Peykan Vanet     Red   80          960     68
6      renault 5  Silver   48          850     38

In [3]:
print(type(df["model"]))
print('--------')
df["model"]

<class 'pandas.core.series.Series'>
--------

0           Peykan
1           BMW X6
2      Peugeot 206
3             Tiba
4    Nissan Junior
5     Peykan Vanet
6        renault 5
Name: model, dtype: object

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">⚠️ نقطه‌گذاری: df.model</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">میانبر، اما محدود</p>
<p style="margin:0 0 14px; text-align:justify;">اگر نام ستون فقط حروف، عدد و زیرخط باشد و با هیچ attribute داخلی DataFrame تداخل نداشته باشد، می‌توان نوشت <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.model</code> به‌جای <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["model"]</code>.</p>
<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
    <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
    <p style="margin:0; text-align:right;">برای ستونی مثل <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Weight (KG)"</code> نمی‌توان از نقطه‌گذاری استفاده کرد — فاصله و پرانتز در نام ستون، براکت را اجباری می‌کند: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["Weight (KG)"]</code>.</p>
  </div>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">روش</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">مثال</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">محدودیت</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["model"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">همیشه کار می‌کند</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">—</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.model</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">کوتاه‌تر</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">نام ساده؛ بدون فاصله و کاراکتر خاص</td></tr></tbody>
  </table>
<p style="margin:10px 0 4px; text-align:justify;">ستون <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Color"</code> را یک‌بار با براکت و یک‌بار با نقطه انتخاب کنید. سپس ستون <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Weight (KG)"</code> را فقط با براکت امتحان کنید.</p>
  <!-- کد را خودت بنویس -->
</div>

In [6]:
df.Color

0       Red
1     White
2     Black
3     White
4      Blue
5       Red
6    Silver
Name: Color, dtype: object

In [ ]:
df.Weight (KG) # --> this code has Error

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">📋 انتخاب چند ستون</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">دو براکت اجباری است</p>
<p style="margin:0 0 14px; text-align:justify;">برای انتخاب همزمان چند ستون، باید یک <strong>لیست</strong> از نام ستون‌ها داخل براکت بگذاریم: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df[["model", "HP", "price"]]</code>. توجه کنید: <strong>دو جفت براکت</strong> — بیرونی برای indexing و درونی برای ساخت لیست پایتون.</p>
<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
    <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
    <p style="margin:0; text-align:right;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["model", "HP"]</code> خطا می‌دهد. حتماً نام ستون‌ها را داخل یک لیست قرار دهید: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df[["model", "HP"]]</code>.</p>
  </div>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">تعداد ستون</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نوع خروجی</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["model"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">۱</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df[["model", "HP"]]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">۲ یا بیشتر</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td></tr></tbody>
  </table>
<p style="margin:10px 0 4px; text-align:justify;">سه ستون <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"model"</code>، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"HP"</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"price"</code> را با هم انتخاب کنید و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">shape</code> خروجی را چاپ کنید.</p>
  <!-- کد را خودت بنویس -->
</div>

In [12]:
df[['model', 'HP', 'price']]

           model   HP  price
0         Peykan   48     33
1         BMW X6  335   2400
2    Peugeot 206  105    105
3           Tiba   87    120
4  Nissan Junior   93    230
5   Peykan Vanet   80     68
6      renault 5   48     38

In [13]:
print(df.shape)

(7, 5)

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🔀 Series در برابر DataFrame</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">تفاوت خروجی را بشناسید</p>
<p style="margin:0 0 14px; text-align:justify;">یک ستون ← <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code> با شکل <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">(n,)</code> (n تعداد ردیف). چند ستون ← <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code> با شکل <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">(n, k)</code> (k تعداد ستون‌های انتخاب‌شده).</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">انتخاب</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">shape نمونه (۷ ردیف)</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نوع</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["model"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">(7,)</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df[["model","HP"]]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">(7, 2)</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td></tr></tbody>
  </table>
<p style="margin:0 0 14px; text-align:justify;">نکته: هر ستون یک DataFrame در واقع یک Series است؛ وقتی از DataFrame یک ستون می‌گیرید، همان Series را دریافت می‌کنید که در فصل Series با آن آشنا شدید.</p>
<p style="margin:10px 0 4px; text-align:justify;">برای <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["HP"]</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df[["model","HP"]]</code> مقدار <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">.shape</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">type()</code> را چاپ کنید و تفاوت را توضیح دهید.</p>
  <!-- کد را خودت بنویس -->
</div>

In [14]:
se = df["HP"]

In [15]:
print(se.shape)
print(type(se))

(7,)
<class 'pandas.core.series.Series'>

In [16]:
df_test = df[['model', 'HP']]

In [17]:
print(df_test.shape)
print(type(df_test))

(7, 2)
<class 'pandas.core.frame.DataFrame'>

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">✅ جمع‌بندی فصل</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">انتخاب ستون</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">هدف</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ستون</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df["col"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ستون (میانبر)</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.col</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">چند ستون</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df[["c1","c2"]]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td></tr></tbody>
  </table>
<p style="margin:0 0 14px; text-align:justify;">در فصل بعد، انتخاب <strong>ردیف</strong> را به‌صورت مفهومی یاد می‌گیریم — سپس ابزارهای دقیق <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> را جداگانه بررسی می‌کنیم.</p>
</div>