# Pandas

In [2]:
import pandas as pd
import numpy as np

## Pandas Methods

### Create DataFrame

In [3]:
data = {
    "name": ["Ali", "Ahmad", "Sina"],
    "age": [20, 26, 21],
    "city": ["Tehran", "Shiraz", "Qom"]
}
creat_df1 = pd.DataFrame(data)
creat_df1

    name  age    city
0    Ali   20  Tehran
1  Ahmad   26  Shiraz
2   Sina   21     Qom

### Open DataFrame

In [11]:
df1 = pd.read_csv("file.csv")
print(type(df1))
df1

<class 'pandas.core.frame.DataFrame'>

     name  math  geo
0   Ahmad    20   18
1    Sina    14   20
2  Mahyar    20   11
3  Farbod    17   13
4   Akbar    19   16

In [12]:
df2 = pd.read_json("file.json")
print(type(df2))
df2

<class 'pandas.core.frame.DataFrame'>

    name  math  jeo
0   JSON    20   16
1  Ahmad    17   12

In [17]:
df3 = pd.read_xml("file.xml")
print(type(df3))
df3

<class 'pandas.core.frame.DataFrame'>

    name  math  geo
0    XML    20   16
1  Ahmad    11   20

## Pandas Attribute

### info, describe

In [20]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   math    5 non-null      int64
 2   geo     5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [21]:
df1.describe()

           math        geo
count   5.00000   5.000000
mean   18.00000  15.600000
std     2.54951   3.646917
min    14.00000  11.000000
25%    17.00000  13.000000
50%    19.00000  16.000000
75%    20.00000  18.000000
max    20.00000  20.000000

In [32]:
mean = df1["math"].mean()
mean

np.float64(18.0)

In [35]:
mean = np.mean(df1["math"].values)
mean

np.float64(18.0)

### Convert DataFrame

In [ ]:
df3.to_csv("converted.csv", index=False)

In [ ]:
df3.to_excel("converted.xlsx", index=False)

In [ ]:
df3.to_json("converted.json", index=False)

## Indexing & slicing

### Column Access

In [22]:
df1

     name  math  geo
0   Ahmad    20   18
1    Sina    14   20
2  Mahyar    20   11
3  Farbod    17   13
4   Akbar    19   16

In [23]:
df1["math"]

0    20
1    14
2    20
3    17
4    19
Name: math, dtype: int64

In [24]:
df1.math

0    20
1    14
2    20
3    17
4    19
Name: math, dtype: int64

In [25]:
df1[["math", "geo", "name"]]

   math  geo    name
0    20   18   Ahmad
1    14   20    Sina
2    20   11  Mahyar
3    17   13  Farbod
4    19   16   Akbar

### Row Access

In [28]:
df1.iloc[0]

name    Ahmad
math       20
geo        18
Name: 0, dtype: object

In [29]:
df1.iloc[1]

name    Sina
math      14
geo       20
Name: 1, dtype: object

### Row & Column Access

In [30]:
df1[["name", "math"]].iloc[0]

name    Ahmad
math       20
Name: 0, dtype: object

In [31]:
df1[["name", "math"]].iloc[1]

name    Sina
math      14
Name: 1, dtype: object