<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

<h2 style="color:#306998; font-size:23px; font-weight:700; border-bottom:1px solid #EAF2F8; padding-bottom:10px; margin:0 0 18px;">📖 loc — انتخاب با برچسب</h2>

<p style="margin:0 0 14px; text-align:justify;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> ابزاری <strong>برچسب‌محور</strong> (label-based) است: برای انتخاب ردیف، ستون، یا هر دو، از نام یا برچسب استفاده می‌کند — نه از موقعیت عددی.</p>

<div style="background:#EAF2F8; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:18px 0; text-align:right; font-weight:600; font-size:18px; color:#306998;">قانون loc: هر چیزی که داخل <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> می‌گذارید باید یک برچسب باشد — برچسب ردیف (index)، نام ستون، یا فهرستی از این برچسب‌ها.</div>

<div style="background:#F8F9FB; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:0 0 26px;">
  <div style="font-weight:700; color:#306998; margin-bottom:6px;">🧠 مدل ذهنی</div>
  <p style="margin:0; text-align:right;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[برچسب_ردیف, برچسب_ستون]</code> — اگر فقط یکی از این دو را بدهید (مثلاً <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6"]</code>)، همان محور فیلتر می‌شود و محور دیگر به‌طور کامل (همه‌ی ستون‌ها) برگردانده می‌شود.</p>
</div>

<hr style="border:none; border-top:1px solid #E6E9ED; margin:22px 0;">

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🏷️ یک ردیف با loc</h3>
<p style="margin:0 0 12px; font-size:14px; color:#78828C;">با برچسب ردیف (index)</p>

<p style="margin:0 0 14px; text-align:justify;">فرض کنید با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.set_index("model")</code> ستون <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">model</code> را به اندیس دیتافریم تبدیل کرده‌اید. حالا با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6"]</code> مستقیماً به ردیفی می‌رسید که برچسبش BMW X6 است. خروجی این دستور یک <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code> است — و چون هر مقدار در این ردیف به یکی از ستون‌های دیتافریم تعلق دارد، اندیس همین Series نیز نام همان ستون‌ها خواهد بود.</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نوع</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6"]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">ردیف مربوط به BMW X6</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["Tiba"]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">ردیف مربوط به Tiba</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td>
    </tr>
  </tbody>
</table>

<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
  <p style="margin:0; text-align:right;">اگر پیش از اجرای <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6"]</code> اندیس را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">set_index</code> تنظیم نکرده باشید، اندیس دیتافریم هنوز همان RangeIndex پیش‌فرض (۰، ۱، ۲، ...) است. در این حالت pandas هیچ برچسبی به نام BMW X6 پیدا نمی‌کند و خطای <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">KeyError</code> می‌دهد. پیش از استفاده از loc با نام‌های دلخواه، همیشه مطمئن شوید اندیس درست تنظیم شده باشد.</p>
</div>

<div style="background:#F1F8F3; border-right:3px solid #4CAF50; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#2E7D32; margin-bottom:6px;">🧪 امتحان کنید</div>
  <p style="margin:0; text-align:right;">دیتافریم خودروها را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.set_index("model")</code> آماده کنید، سپس ردیف <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Peugeot 206"</code> را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> انتخاب کنید.</p>
</div>
<!-- سلول کد بعدی: loc را برای Peugeot 206 اینجا امتحان کنید -->

</div>

In [1]:
import pandas as pd
import numpy as np

In [2]:
cars_dictionary = {
    "model" :[ "Peykan", "BMW X6", "Peugeot 206", "Tiba", "Nissan Junior", "Peykan Vanet", "renault 5"],
    "Color" :["Red", "White", "Black", "White", "Blue", "Red", "Silver"],
    "HP" :[48, 335, 105, 87, 93, 80, 48],
    "Weight (KG)": [990, 2320, 1025, 1027, 1540, 960, 850],
    "price" :[33, 2400, 105, 120, 230, 68, 38]
}
df = pd.DataFrame(cars_dictionary)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

           model   Color   HP  Weight (KG)  price
0         Peykan     Red   48          990     33
1         BMW X6   White  335         2320   2400
2    Peugeot 206   Black  105         1025    105
3           Tiba   White   87         1027    120
4  Nissan Junior    Blue   93         1540    230
5   Peykan Vanet     Red   80          960     68
6      renault 5  Silver   48          850     38

In [4]:
df.set_index("model", inplace=True)

In [5]:
df

                Color   HP  Weight (KG)  price
model
Peykan            Red   48          990     33
BMW X6          White  335         2320   2400
Peugeot 206     Black  105         1025    105
Tiba            White   87         1027    120
Nissan Junior    Blue   93         1540    230
Peykan Vanet      Red   80          960     68
renault 5      Silver   48          850     38

In [6]:
df.loc['Peugeot 206']

Color          Black
HP               105
Weight (KG)     1025
price            105
Name: Peugeot 206, dtype: object

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🏷️ چند ردیف و slice برچسبی</h3>
<p style="margin:0 0 12px; font-size:14px; color:#78828C;">با لیست یا بازه‌ی برچسبی</p>

<p style="margin:0 0 14px; text-align:justify;">علاوه بر یک برچسب تکی، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> دو راه دیگر هم برای گرفتن چند ردیف با هم دارد: یک <strong>فهرست</strong> از برچسب‌ها، یا یک <strong>بازه‌ی</strong> برچسبی.</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">روش</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نکته</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">فهرست برچسب‌ها</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[["Peykan", "Tiba", "BMW X6"]]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">حتی با فهرستی از یک عضو هم DataFrame می‌دهد، نه Series</td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">بازه‌ی برچسبی (slice)</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["Peugeot 206":"Tiba"]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">برخلاف اسلایس موقعیتی، هر دو سرِ بازه در نتیجه گنجانده می‌شوند</td>
    </tr>
  </tbody>
</table>

<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
  <p style="margin:0; text-align:right;">برش برچسبی وقتی معنای روشنی دارد که index به‌صورت یکنواخت مرتب (monotonic) باشد. روی index نامرتب، pandas ممکن است خطا بدهد یا ردیف‌هایی برگرداند که با انتظار شما — یعنی «همه‌چیز بین این دو برچسب» — همخوانی نداشته باشد. در صورت نیاز، پیش از slice برچسبی از <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">sort_index()</code> استفاده کنید.</p>
</div>

<div style="background:#F1F8F3; border-right:3px solid #4CAF50; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#2E7D32; margin-bottom:6px;">🧪 امتحان کنید</div>
  <p style="margin:0; text-align:right;">سه خودرو <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Peykan"</code>، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Tiba"</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"BMW X6"</code> را با فهرستِ <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> انتخاب کنید. سپس بازه‌ی <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Peugeot 206":"Tiba"</code> را امتحان کنید.</p>
</div>
<!-- سلول کد بعدی: فهرست و بازه‌ی loc را اینجا امتحان کنید -->

</div>

In [7]:
df.loc[['Peykan', 'Tiba', "BMW X6"]]

        Color   HP  Weight (KG)  price
model
Peykan    Red   48          990     33
Tiba    White   87         1027    120
BMW X6  White  335         2320   2400

In [8]:
df.loc['Peugeot 206': 'Tiba']

             Color   HP  Weight (KG)  price
model
Peugeot 206  Black  105         1025    105
Tiba         White   87         1027    120

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">📋 انتخاب ستون با loc</h3>
<p style="margin:0 0 12px; font-size:14px; color:#78828C;">با برچسب ستون</p>

<p style="margin:0 0 14px; text-align:justify;">همان‌طور که پیش‌تر دیدید، آرگومان اول <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> مربوط به ردیف است و آرگومان دوم مربوط به ستون. برای گرفتن یک یا چند ستون از <strong>همه‌ی</strong> ردیف‌ها، جای آرگومان ردیف را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">:</code> پر می‌کنید — یعنی «همه‌ی ردیف‌ها».</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">معنا</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نوع</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[:, "HP"]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">ستون HP، برای همه‌ی ردیف‌ها</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[:, ["Color", "price"]]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">ستون‌های Color و price، برای همه‌ی ردیف‌ها</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td>
    </tr>
  </tbody>
</table>

<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
  <p style="margin:0; text-align:right;">فراموش نکنید <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">:,</code> را قبل از نام ستون بیاورید. اگر به‌جای <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[:, "HP"]</code> فقط بنویسید <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["HP"]</code>، pandas آن را جست‌وجوی یک <strong>ردیف</strong> با برچسب HP تفسیر می‌کند — چون آرگومان اول loc همیشه ردیف است، نه ستون — و معمولاً با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">KeyError</code> مواجه می‌شوید.</p>
</div>

<div style="background:#F1F8F3; border-right:3px solid #4CAF50; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#2E7D32; margin-bottom:6px;">🧪 امتحان کنید</div>
  <p style="margin:0; text-align:right;">با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> فقط ستون‌های <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Color"</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"price"</code> را برای تمام ردیف‌ها انتخاب کنید.</p>
</div>
<!-- سلول کد بعدی: انتخاب ستون‌های Color و price را اینجا امتحان کنید -->

</div>

In [9]:
# df.loc['HP'] --> First Argument only for rows

In [10]:
df.loc[:, "HP"]

model
Peykan            48
BMW X6           335
Peugeot 206      105
Tiba              87
Nissan Junior     93
Peykan Vanet      80
renault 5         48
Name: HP, dtype: int64

In [11]:
df.loc[:, ["Color", "price"]]

                Color  price
model
Peykan            Red     33
BMW X6          White   2400
Peugeot 206     Black    105
Tiba            White    120
Nissan Junior    Blue    230
Peykan Vanet      Red     68
renault 5      Silver     38

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🎯 ترکیب ردیف و ستون</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">یک سلول تا یک زیرجدول</p>
<p style="margin:0 0 14px; text-align:justify;">یک مقدار (اسکالر): <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6", "price"]</code></p>
<p style="margin:0 0 14px; text-align:justify;">یک ردیف، چند ستون: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6", ["Color", "price"]]</code> → <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></p>
<p style="margin:0 0 14px; text-align:justify;">چند ردیف، چند ستون: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[["Peykan", "BMW X6"], ["Color", "HP"]]</code> → <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">هدف</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک سلول</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6", "price"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">اسکالر</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ردیف، چند ستون</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6", ["Color","price"]]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">زیرجدول</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[["Peykan","BMW X6"], ["HP","price"]]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td></tr></tbody>
  </table>
<p style="margin:10px 0 4px; text-align:justify;">قیمت <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Tiba"</code> را به‌صورت اسکالر بگیرید. سپس زیرجدولی از <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Peykan"</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"BMW X6"</code> با ستون‌های <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"HP"</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"price"</code> بسازید.</p>
  <!-- کد را خودت بنویس -->
</div>

In [12]:
df

                Color   HP  Weight (KG)  price
model
Peykan            Red   48          990     33
BMW X6          White  335         2320   2400
Peugeot 206     Black  105         1025    105
Tiba            White   87         1027    120
Nissan Junior    Blue   93         1540    230
Peykan Vanet      Red   80          960     68
renault 5      Silver   48          850     38

### 1

In [13]:
df.loc["Tiba", 'price']

np.int64(120)

### 2

In [14]:
df.loc[["BMW X6", "Peykan"], ["HP", "price"]]

         HP  price
model
BMW X6  335   2400
Peykan   48     33

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">✅ جمع‌بندی فصل</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">loc</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">کاربرد</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">الگو</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ردیف</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["label"]</code></td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">چند ردیف</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[["l1","l2"]]</code></td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">بازه برچسبی</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["start":"end"]</code></td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">ستون(ها)</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[:, "col"]</code> یا <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[:, ["c1","c2"]]</code></td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">سلول / زیرجدول</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[row, col]</code></td></tr></tbody>
  </table>
<p style="margin:0 0 14px; text-align:justify;">فصل بعد: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> — همان کارها، اما با موقعیت عددی.</p>
</div>