<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

<h2 style="color:#306998; font-size:23px; font-weight:700; border-bottom:1px solid #EAF2F8; padding-bottom:10px; margin:0 0 18px;">📖 iloc — انتخاب با موقعیت</h2>

<p style="margin:0 0 14px; text-align:justify;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> ابزاری <strong>موقعیت‌محور</strong> (position-based) است: برای انتخاب ردیف، ستون، یا هر دو، از عدد صحیح استفاده می‌کند — نه از برچسب. برچسب index در این حالت اصلاً اهمیتی ندارد.</p>

<div style="background:#EAF2F8; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:18px 0; text-align:right; font-weight:600; font-size:18px; color:#306998;">قانون iloc: هر چیزی که داخل <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> می‌گذارید باید یک موقعیت عددی باشد — ۰، ۱، ۲، ...، یک slice مثل <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">1:4</code>، یا فهرستی از موقعیت‌ها.</div>

<div style="background:#F8F9FB; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:0 0 26px;">
  <div style="font-weight:700; color:#306998; margin-bottom:6px;">🧠 مدل ذهنی</div>
  <p style="margin:0; text-align:right;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[موقعیت_ردیف, موقعیت_ستون]</code> — اگر فقط یکی از این دو را بدهید (مثلاً <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[0]</code>)، همان محور فیلتر می‌شود و محور دیگر به‌طور کامل برگردانده می‌شود. مثل اندیس آرایه یا لیست در پایتون، شمارش از صفر شروع می‌شود.</p>
</div>

<hr style="border:none; border-top:1px solid #E6E9ED; margin:22px 0;">

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🔢 یک ردیف با iloc</h3>
<p style="margin:0 0 12px; font-size:14px; color:#78828C;">با موقعیت عددی (۰، ۱، ۲، ...)</p>

<p style="margin:0 0 14px; text-align:justify;">با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[0]</code> به ردیفی می‌رسید که در موقعیت ۰ قرار دارد — یعنی اولین ردیف جدول. درست مثل loc، وقتی با یک موقعیت تکی ردیف را انتخاب می‌کنید، خروجی یک <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code> است که اندیسش همان نام ستون‌های دیتافریم است.</p>

<p style="margin:0 0 14px; text-align:justify;">با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[2]</code> همیشه ردیفی را می‌گیرید که در موقعیت ۲ قرار دارد (یعنی سومین ردیف) — کاملاً بدون توجه به اینکه برچسب index آن ردیف چیست. این دقیقاً همان تفاوت اصلی loc و iloc است که پیش‌تر دیدید: iloc فقط به موقعیت نگاه می‌کند، نه به برچسب.</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">معنا</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نوع</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[0]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">اولین ردیف</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[-1]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">آخرین ردیف</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td>
    </tr>
  </tbody>
</table>

<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
  <p style="margin:0; text-align:right;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> فقط موقعیت عددی می‌پذیرد، نه برچسب. اگر بنویسید <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc["BMW X6"]</code>، چون "BMW X6" یک رشته است نه یک عدد صحیح، با خطای <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">TypeError</code> مواجه می‌شوید. برای دسترسی با نام، سراغ loc بروید نه iloc.</p>
</div>

<div style="background:#F1F8F3; border-right:3px solid #4CAF50; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#2E7D32; margin-bottom:6px;">🧪 امتحان کنید</div>
  <p style="margin:0; text-align:right;">بدون <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">set_index</code>، ردیف اول را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> بگیرید. سپس index را با یک ستون دلخواه عوض کنید و دوباره <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc[0]</code> را اجرا کنید — آیا هنوز همان ردیف قبلی را می‌گیرید؟ چرا؟</p>
</div>
<!-- سلول کد بعدی: iloc را قبل و بعد از تغییر index اینجا امتحان کنید -->

</div>

In [2]:
import numpy as np
import pandas as pd

In [3]:
cars_dictionary = {
    "model" :[ "Peykan", "BMW X6", "Peugeot 206", "Tiba", "Nissan Junior", "Peykan Vanet", "renault 5"],
    "Color" :["Red", "White", "Black", "White", "Blue", "Red", "Silver"],
    "HP" :[48, 335, 105, 87, 93, 80, 48],
    "Weight (KG)": [990, 2320, 1025, 1027, 1540, 960, 850],
    "price" :[33, 2400, 105, 120, 230, 68, 38]
}
df = pd.DataFrame(cars_dictionary)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

           model   Color   HP  Weight (KG)  price
0         Peykan     Red   48          990     33
1         BMW X6   White  335         2320   2400
2    Peugeot 206   Black  105         1025    105
3           Tiba   White   87         1027    120
4  Nissan Junior    Blue   93         1540    230
5   Peykan Vanet     Red   80          960     68
6      renault 5  Silver   48          850     38

In [8]:
df.iloc[1]

model          BMW X6
Color           White
HP                335
Weight (KG)      2320
price            2400
Name: 1, dtype: object

In [6]:
df_test = df.set_index("model")
df_test

                Color   HP  Weight (KG)  price
model
Peykan            Red   48          990     33
BMW X6          White  335         2320   2400
Peugeot 206     Black  105         1025    105
Tiba            White   87         1027    120
Nissan Junior    Blue   93         1540    230
Peykan Vanet      Red   80          960     68
renault 5      Silver   48          850     38

In [9]:
df.iloc[1]

model          BMW X6
Color           White
HP                335
Weight (KG)      2320
price            2400
Name: 1, dtype: object

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🔢 چند ردیف و slice موقعیتی</h3>
<p style="margin:0 0 12px; font-size:14px; color:#78828C;">با لیست یا بازه‌ی موقعیتی</p>

<p style="margin:0 0 14px; text-align:justify;">علاوه بر یک موقعیت تکی، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> هم دو راه دیگر برای گرفتن چند ردیف با هم دارد: یک <strong>فهرست</strong> از موقعیت‌ها، یا یک <strong>بازه‌ی</strong> موقعیتی.</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">روش</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نکته</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">فهرست موقعیت‌ها</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[[0, 2, 4]]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">حتی با فهرستی از یک عضو هم DataFrame می‌دهد، نه Series</td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">بازه‌ی موقعیتی (slice)</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[1:4]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">ردیف‌های موقعیت ۱، ۲، ۳ — موقعیت ۴ شامل نمی‌شود</td>
    </tr>
  </tbody>
</table>

<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
  <p style="margin:0; text-align:right;">در <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc[1:4]</code> انتهای بازه exclusive است — دقیقاً مثل slice معمولی در پایتون (لیست، رشته و غیره). این با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> فرق دارد: در بازه‌ی برچسبی loc، هر دو سرِ بازه inclusive هستند. یک نکته‌ی مثبت هم هست: چون iloc فقط به موقعیت نگاه می‌کند نه به برچسب، لازم نیست index مرتب باشد — رفتار بازه‌ی موقعیتی همیشه قابل‌پیش‌بینی است.</p>
</div>

<div style="background:#F1F8F3; border-right:3px solid #4CAF50; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#2E7D32; margin-bottom:6px;">🧪 امتحان کنید</div>
  <p style="margin:0; text-align:right;">با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> ردیف‌های موقعیت ۰، ۲ و ۴ را با فهرست انتخاب کنید. سپس بازه‌ی <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">1:4</code> را امتحان کنید و تعداد ردیف‌های خروجی را بشمارید — آیا با انتظار شما یکی است؟</p>
</div>
<!-- سلول کد بعدی: فهرست و بازه‌ی iloc را اینجا امتحان کنید -->

</div>

In [10]:
df.iloc[[0, 2, 4]]

           model  Color   HP  Weight (KG)  price
0         Peykan    Red   48          990     33
2    Peugeot 206  Black  105         1025    105
4  Nissan Junior   Blue   93         1540    230

In [11]:
df.iloc[1:4]

         model  Color   HP  Weight (KG)  price
1       BMW X6  White  335         2320   2400
2  Peugeot 206  Black  105         1025    105
3         Tiba  White   87         1027    120

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">📋 انتخاب ستون با iloc</h3>
<p style="margin:0 0 12px; font-size:14px; color:#78828C;">با موقعیت ستون</p>

<p style="margin:0 0 14px; text-align:justify;">همان‌طور که پیش‌تر دیدید، آرگومان اول <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> مربوط به ردیف است و آرگومان دوم مربوط به ستون. برای گرفتن یک یا چند ستون از همه‌ی ردیف‌ها، جای آرگومان ردیف را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">:</code> پر می‌کنید — مثلاً <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[:, 1]</code> دومین ستون (موقعیت ۱) را از همه‌ی ردیف‌ها می‌گیرد.</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سینتکس</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">معنا</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نوع</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[:, 0]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">ستون اول، برای همه‌ی ردیف‌ها</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[:, [0, 2]]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">ستون‌های اول و سوم، برای همه‌ی ردیف‌ها</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td>
    </tr>
  </tbody>
</table>

<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
  <p style="margin:0; text-align:right;">فراموش نکنید <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">:,</code> را قبل از موقعیت ستون بیاورید. اگر به‌جای <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[:, 1]</code> فقط بنویسید <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[1]</code>، pandas آن را انتخابِ ردیفی در موقعیت ۱ تفسیر می‌کند، نه ستون. این حتی خطرناک‌تر از اشتباه مشابه در loc است: چون ۱ یک موقعیت معتبر برای ردیف هم هست، pandas هیچ خطایی نمی‌دهد — فقط بی‌سروصدا یک ردیفِ اشتباه (به‌جای ستونی که می‌خواستید) برمی‌گرداند.</p>
</div>

<div style="background:#F1F8F3; border-right:3px solid #4CAF50; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#2E7D32; margin-bottom:6px;">🧪 امتحان کنید</div>
  <p style="margin:0; text-align:right;">ستون‌های اول، سوم و پنجم را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> انتخاب کنید (با لیست موقعیت).</p>
</div>
<!-- سلول کد بعدی: انتخاب ستون‌های اول، سوم و پنجم را اینجا امتحان کنید -->

</div>

In [17]:
df.iloc[:, [1, 3, 4]]

    Color  Weight (KG)  price
0     Red          990     33
1   White         2320   2400
2   Black         1025    105
3   White         1027    120
4    Blue         1540    230
5     Red          960     68
6  Silver          850     38

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🎯 ترکیب ردیف و ستون</h3>
<p style="margin:0 0 12px; font-size:14px; color:#78828C;">زیرجدول موقعیتی</p>

<p style="margin:0 0 14px; text-align:justify;">پیش‌تر دیدید که دادن یک موقعیت تکی یا یک فهرست، نوع خروجی را عوض می‌کند. وقتی هر دو آرگومان <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> — هم ردیف، هم ستون — را همزمان می‌دهید، همین قانون روی هر دو محور با هم اعمال می‌شود:</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">ردیف</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">ستون</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">مثال</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">موقعیت تکی</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">موقعیت تکی</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[1, 4]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">یک مقدار تکی (scalar)</td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">موقعیت تکی</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">فهرست</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[1, [0, 4]]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">Series — اندیسش نام ستون‌های انتخابی است</td>
    </tr>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">فهرست</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">موقعیت تکی</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[[0, 2], 1]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">Series — اندیسش برچسب ردیف‌های انتخابی است</td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">فهرست</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">فهرست</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[[0, 2], [1, 3]]</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">DataFrame — یک زیرجدول کامل</td>
    </tr>
  </tbody>
</table>

<p style="margin:0 0 14px; text-align:justify;">به‌جای این ترکیب مستقیم، گاهی این شکل را هم می‌بینید: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df[["model", "price"]].iloc[0]</code> — یعنی اول ستون‌ها را با براکت معمولی انتخاب کنید، بعد یک ردیف را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> از همان نتیجه بگیرید. برای <strong>خواندن</strong> داده، نتیجه با ترکیب مستقیم یکسان است.</p>

<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
  <p style="margin:0; text-align:right;">این روش زنجیره‌ای فقط برای <strong>خواندن</strong> داده امن است. اگر بخواهید با همین الگو مقداری را <strong>تغییر</strong> دهید — مثلاً <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df[["price"]].iloc[0] = 100</code> — ممکن است با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">SettingWithCopyWarning</code> مواجه شوید و تغییرتان اصلاً روی دیتافریم اصلی اعمال نشود، چون در واقع روی یک کپی موقت کار کرده‌اید. برای تغییر مقدار، همیشه از ترکیب مستقیم مثل <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[0, 3] = 100</code> استفاده کنید.</p>
</div>

<div style="background:#F1F8F3; border-right:3px solid #4CAF50; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#2E7D32; margin-bottom:6px;">🧪 امتحان کنید</div>
  <p style="margin:0; text-align:right;">با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> مقداری را بگیرید که در موقعیت ردیف ۲ و موقعیت ستون ۳ قرار دارد. سپس با فهرست، زیرجدولی از ردیف‌های موقعیت ۰ و ۲ و ستون‌های موقعیت ۱ و ۲ بسازید.</p>
</div>
<!-- سلول کد بعدی: ترکیب ردیف و ستون را اینجا امتحان کنید -->

</div>

In [18]:
df.iloc[2, 3]

np.int64(1025)

In [19]:
df.iloc[[0, 2], [1, 2]]

   Color   HP
0    Red   48
2  Black  105

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">⚖️ loc در برابر iloc</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">جدول مقایسه</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">ویژگی</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code></th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code></th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">بر اساس</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">برچسب</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">موقعیت عددی</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ردیف</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["label"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[0]</code></td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">چند ردیف</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[["l1","l2"]]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[[0,1]]</code></td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">slice</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">هر دو inclusive</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">انتها exclusive</td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">ستون</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc[:, "col"]</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[:, 0]</code></td></tr></tbody>
  </table>
<p style="margin:10px 0 4px; text-align:justify;">برای همان DataFrame با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">set_index("model")</code>، ردیف <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"BMW X6"</code> را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> و ردیف اول را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> بگیرید. آیا همیشه یکسان‌اند؟</p>
  <!-- کد را خودت بنویس -->
</div>

In [20]:
df_test

                Color   HP  Weight (KG)  price
model
Peykan            Red   48          990     33
BMW X6          White  335         2320   2400
Peugeot 206     Black  105         1025    105
Tiba            White   87         1027    120
Nissan Junior    Blue   93         1540    230
Peykan Vanet      Red   80          960     68
renault 5      Silver   48          850     38

In [22]:
df_test.loc["BMW X6"]

Color          White
HP               335
Weight (KG)     2320
price           2400
Name: BMW X6, dtype: object

In [24]:
df.iloc[1]

model          BMW X6
Color           White
HP                335
Weight (KG)      2320
price            2400
Name: 1, dtype: object

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">✅ جمع‌بندی فصل</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">iloc</p>
<p style="margin:0 0 14px; text-align:justify;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> برای وقتی که موقعیت را می‌دانیم؛ <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> برای وقتی که برچسب را می‌دانیم. در فصل بعد <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">at</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iat</code> را برای دسترسی سریع به <strong>یک سلول</strong> می‌بینیم.</p>
</div>