<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h2 style="color:#306998; font-size:23px; font-weight:700; border-bottom:1px solid #EAF2F8; padding-bottom:10px; margin:0 0 18px;">
    📖 کاوش در داده‌ها
  </h2>

  <p style="margin:0 0 14px; text-align:justify;">
    در فصل قبل یاد گرفتیم چگونه داده را از منابع مختلف بخوانیم. اما بلافاصله پس از خواندن یک فایل، هنوز نمی‌دانیم دقیقاً با چه داده‌ای طرف هستیم: چند ردیف دارد؟ ستون‌ها چه نامی دارند؟ آیا مقدار خالی وجود دارد؟ این فصل مجموعه‌ای از ابزارهای پانداس را معرفی می‌کند که پیش از هر تحلیلی، یک شناخت اولیه و سریع از داده به ما می‌دهند.
  </p>

  <div style="background:#EAF2F8; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:18px 0; text-align:right; font-weight:600; font-size:18px; color:#306998;">
    این ابزارها دو نوع‌اند: Attribute (بدون پرانتز؛ فقط اطلاعاتی از پیش موجود را نشان می‌دهد) و Method (با پرانتز؛ عملیاتی روی داده اجرا می‌کند). این تفاوت را در ادامه‌ی همین فصل، برای هر مورد مشخص کرده‌ایم.
  </div>

  <div style="background:#F8F9FB; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:0 0 26px;">
    <div style="font-weight:700; color:#306998; margin-bottom:6px;">🧠 مدل ذهنی</div>
    <p style="margin:0; text-align:right;">
      این دوازده ابزار در واقع پاسخ به چهار سؤال ساده‌اند: داده چه شکلی است؟ (head، tail، sample) — چقدر بزرگ است؟ (shape، size، ndim) — چه برچسب و نوع داده‌ای دارد؟ (columns، index، dtypes) — و در یک نگاه جامع، وضعیت کلی‌اش چطور است؟ (info، describe، memory_usage)
    </p>
  </div>

  <hr style="border:none; border-top:1px solid #E6E9ED; margin:22px 0;">

  <h3 style="color:#306998; font-size:18px; margin:0 0 6px;">👀 نگاه اول به داده</h3>
  <p style="margin:0 0 12px; font-size:14px; color:#78828C;">Attribute نیستند؛ Method‌اند و باید با پرانتز فراخوانی شوند</p>

  <p style="margin:0 0 14px; text-align:justify;">
    اولین قدم در مواجهه با هر DataFrame جدید، یک نگاه سریع به چند ردیف از آن است، بدون آنکه کل داده (که ممکن است میلیون‌ها ردیف باشد) چاپ شود.
  </p>

  <table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead>
      <tr style="background:#EAF2F8;">
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">متد</th>
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">کدام ردیف‌ها</th>
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">تعداد پیش‌فرض</th>
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">چه زمانی مفید است</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">head()</code></td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">از ابتدای داده</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">پنج ردیف</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">بررسی سریع نام و نوع ستون‌ها</td>
      </tr>
      <tr style="background:#FAFBFC;">
        <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">tail()</code></td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">از انتهای داده</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">پنج ردیف</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">بررسی ردیف‌های پایانی، مثلاً در داده‌ی زمانی</td>
      </tr>
      <tr>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">sample()</code></td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">تصادفی</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ردیف</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">نمونه‌ی بی‌طرفانه، خصوصاً وقتی داده مرتب‌شده است</td>
      </tr>
    </tbody>
  </table>

  <p style="margin:0 0 4px; text-align:justify;">
    نکته‌ی مهم: اگر داده بر اساس یک ستون مرتب شده باشد (مثلاً تاریخ)، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">head()</code> تصویر واقعی و متنوعی از کل داده نمی‌دهد؛ در چنین مواردی <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">sample()</code> انتخاب بهتری است.
  </p>
  <p style="margin:10px 0 4px; text-align:justify;">
    یک DataFrame دلخواه بسازید و هر سه‌ی <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">head()</code>، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">tail()</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">sample()</code> را روی آن اجرا و خروجی‌ها را با هم مقایسه کنید.
  </p>
  <!-- کد را خودت بنویس -->

In [24]:
import pandas as pd
cars_dictionary = {
    "model" :[ "Peykan", "BMW X6", "Peugeot 206", "Tiba", "Nissan Junior", "Peykan Vanet", "renault 5"],
    "Color" :["Red", "White", "Black", "White", "Blue", "Red", "Silver"],
    "HP" :[48, 335, 105, 87, 93, 80, 48],
    "Weight (KG)": [990, 2320, 1025, 1027, 1540, 960, 850],
    "price" :[33, 2400, 105, 120, 230, 68, 38]
}

df = pd.DataFrame(cars_dictionary)
df

           model   Color   HP  Weight (KG)  price
0         Peykan     Red   48          990     33
1         BMW X6   White  335         2320   2400
2    Peugeot 206   Black  105         1025    105
3           Tiba   White   87         1027    120
4  Nissan Junior    Blue   93         1540    230
5   Peykan Vanet     Red   80          960     68
6      renault 5  Silver   48          850     38

## head()

In [3]:
df.head()
# df.head(3)

           model  Color   HP  Weight (KG)  price
0         Peykan    Red   48          990     33
1         BMW X6  White  335         2320   2400
2    Peugeot 206  Black  105         1025    105
3           Tiba  White   87         1027    120
4  Nissan Junior   Blue   93         1540    230

## tail()

In [4]:
df.tail()
# df.tail(2)

           model   Color   HP  Weight (KG)  price
2    Peugeot 206   Black  105         1025    105
3           Tiba   White   87         1027    120
4  Nissan Junior    Blue   93         1540    230
5   Peykan Vanet     Red   80          960     68
6      renault 5  Silver   48          850     38

## sample()

In [7]:
df.sample()

           model Color  HP  Weight (KG)  price
4  Nissan Junior  Blue  93         1540    230

In [8]:
df.sample(3)

           model   Color  HP  Weight (KG)  price
3           Tiba   White  87         1027    120
6      renault 5  Silver  48          850     38
4  Nissan Junior    Blue  93         1540    230

In [10]:
df.sample(3, ignore_index=True)

           model  Color  HP  Weight (KG)  price
0           Tiba  White  87         1027    120
1         Peykan    Red  48          990     33
2  Nissan Junior   Blue  93         1540    230

In [12]:
df.sample(3, ignore_index=True, random_state=42)

          model  Color   HP  Weight (KG)  price
0        Peykan    Red   48          990     33
1        BMW X6  White  335         2320   2400
2  Peykan Vanet    Red   80          960     68

## ____________________________________________________________________________________________________

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

  <h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">📏 ابعاد و اندازه</h3>
  <p style="margin:0 0 12px; font-size:14px; color:#78828C;">Attribute‌اند؛ بدون پرانتز فراخوانی می‌شوند</p>

  <p style="margin:0 0 14px; text-align:justify;">
    این سه ویژگی، بدون هیچ محاسبه‌ی اضافه‌ای، اطلاعات پایه درباره‌ی بزرگی DataFrame را فوراً در اختیار می‌گذارند.
  </p>

  <table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead>
      <tr style="background:#EAF2F8;">
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">ویژگی</th>
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی</th>
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">معنا</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">shape</code></td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">یک tuple به‌صورت (تعداد ردیف، تعداد ستون)</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">ابعاد کلی جدول</td>
      </tr>
      <tr style="background:#FAFBFC;">
        <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">size</code></td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">یک عدد صحیح</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">تعداد کل عناصر (تعداد ردیف ضرب‌در تعداد ستون)</td>
      </tr>
      <tr>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">ndim</code></td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">یک عدد صحیح</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">تعداد ابعاد؛ برای DataFrame همیشه دو و برای Series همیشه یک</td>
      </tr>
    </tbody>
  </table>

  <p style="margin:0 0 4px; text-align:justify;">
    توجه کنید <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">ndim</code> همان مفهومی است که در فصل Series دیدیم: Series یک‌بعدی و DataFrame دوبعدی است؛ این ویژگی همان تفاوت را به‌صورت عددی گزارش می‌دهد.
  </p>
  <p style="margin:10px 0 4px; text-align:justify;">
    برای همان DataFrame، مقادیر <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">shape</code>، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">size</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">ndim</code> را چاپ کنید و بررسی کنید رابطه‌ی size = تعداد ردیف × تعداد ستون برقرار است.
  </p>
  <!-- کد را خودت بنویس -->

In [13]:
data = [
    ["Ahmad", 26, "Ph.D", "Tehran"],
    ["Vahid", 29, "Bachelor", "Gilan"],
    ["Soheil", 24, "Diploma", "Tabriz"],
    ["Mehran", 24, "Diploma", "Sarab"],
    ["Bahman", 55, "Master", "Tehran"],
    ["Ariana", 23, "Bachelor", "Tehran"]
    
]
persons_df = pd.DataFrame(data=data, 
                          index=[1, 2, 3, 4, 5, 6], 
                          columns=['Name', 'Age', "Grade", "City"])
print(type(persons_df))
persons_df

<class 'pandas.DataFrame'>

     Name  Age     Grade    City
1   Ahmad   26      Ph.D  Tehran
2   Vahid   29  Bachelor   Gilan
3  Soheil   24   Diploma  Tabriz
4  Mehran   24   Diploma   Sarab
5  Bahman   55    Master  Tehran
6  Ariana   23  Bachelor  Tehran

## shape

In [14]:
persons_df.shape

(6, 4)

## size

In [15]:
persons_df.size

24

## ndim

In [16]:
persons_df.ndim

2

## ____________________________________________________________________________________________________

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🏷️ برچسب‌ها و نوع داده</h3>
  <p style="margin:0 0 12px; font-size:14px; color:#78828C;">Attribute‌اند؛ بدون پرانتز فراخوانی می‌شوند</p>

  <p style="margin:0 0 14px; text-align:justify;">
    <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">columns</code> نام ستون‌ها و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">index</code> برچسب ردیف‌ها را برمی‌گردانند؛ هر دو از نوع شیء Index هستند، فقط روی محور متفاوتی قرار دارند (columns روی axis=1 و index روی axis=0). <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">dtypes</code> هم برای هر ستون، نوع داده‌اش را برمی‌گرداند؛ خروجی آن یک Series است که index آن نام ستون‌هاست و مقدارش، dtype متناظر.
  </p>
  <p style="margin:0 0 4px; text-align:justify;">
    <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">columns</code>، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">index</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">dtypes</code> آن DataFrame را چاپ کنید و با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">type()</code> بررسی کنید خروجی columns و index واقعاً از یک جنس‌اند.
  </p>
  <!-- کد را خودت بنویس -->

In [17]:
df = pd.DataFrame([['Peykan', 'Red', 48, 990, 33],
       ['BMW X6', 'White', 335, 2320, 2400],
       ['Peugeot 206', 'Black', 105, 1025, 105],
       ['Tiba', 'White', 87, 1027, 120],
       ['Nissan Junior', 'Blue', 93, 1540, 230],
       ['Nissan Junior', 'Red', 93, 1540, 186],
       ['renault 5', 'Silver', 48, 850, 38]],
       index = ['a','b','c','d','e','f','g'],
       columns= ['model' , 'Color' , 'HP', 'Weight (KG)', 'price'])
df

           model   Color   HP  Weight (KG)  price
a         Peykan     Red   48          990     33
b         BMW X6   White  335         2320   2400
c    Peugeot 206   Black  105         1025    105
d           Tiba   White   87         1027    120
e  Nissan Junior    Blue   93         1540    230
f  Nissan Junior     Red   93         1540    186
g      renault 5  Silver   48          850     38

## columns

In [19]:
df.columns

Index(['model', 'Color', 'HP', 'Weight (KG)', 'price'], dtype='str')

### Convert to List

In [20]:
df.columns.tolist()

['model', 'Color', 'HP', 'Weight (KG)', 'price']

## index

In [21]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')

### Convert to list

In [22]:
df.index.tolist()

['a', 'b', 'c', 'd', 'e', 'f', 'g']

## dtypes

In [23]:
df.dtypes

model            str
Color            str
HP             int64
Weight (KG)    int64
price          int64
dtype: object

## ____________________________________________________________________________________________________

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
  <h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🔍 خلاصه‌ی جامع</h3>
  <p style="margin:0 0 12px; font-size:14px; color:#78828C;">Method‌اند و باید با پرانتز فراخوانی شوند</p>

  <p style="margin:0 0 14px; text-align:justify;">
    این دو متد، چند ویژگی بالا را در یک گزارش واحد کنار هم می‌آورند، اما هدف‌شان کاملاً متفاوت است: یکی سلامت ساختاری داده را نشان می‌دهد، دیگری توزیع آماری آن را.
  </p>

  <table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead>
      <tr style="background:#EAF2F8;">
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">متد</th>
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">هدف</th>
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">ستون‌های پوشش‌داده‌شده</th>
        <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">خروجی شامل چیست</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">info()</code></td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">بررسی ساختار و سلامت داده</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">همه‌ی ستون‌ها</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">تعداد ردیف، dtype هر ستون، تعداد مقادیر غیرخالی، حجم حافظه</td>
      </tr>
      <tr style="background:#FAFBFC;">
        <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">describe()</code></td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">بررسی آماری توزیع داده</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">پیش‌فرض فقط ستون‌های عددی</td>
        <td style="padding:10px 12px; border:1px solid #E6E9ED;">count، mean، std، min، چارک‌ها، max</td>
      </tr>
    </tbody>
  </table>

  <p style="margin:0 0 4px; text-align:justify;">
    نکته: برای دیدن آمار ستون‌های غیرعددی (مثل رشته‌ها) هم، می‌توان از <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">describe(include='all')</code> استفاده کرد.
  </p>
  <p style="margin:10px 0 4px; text-align:justify;">
    یک بار <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">info()</code> و یک بار <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">describe()</code> را روی DataFrame اجرا کنید و تفاوت خروجی‌ها را با هم مقایسه کنید.
  </p>
  <!-- کد را خودت بنویس -->

## info()

In [25]:
df

           model   Color   HP  Weight (KG)  price
0         Peykan     Red   48          990     33
1         BMW X6   White  335         2320   2400
2    Peugeot 206   Black  105         1025    105
3           Tiba   White   87         1027    120
4  Nissan Junior    Blue   93         1540    230
5   Peykan Vanet     Red   80          960     68
6      renault 5  Silver   48          850     38

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   model        7 non-null      str
 1   Color        7 non-null      str
 2   HP           7 non-null      int64
 3   Weight (KG)  7 non-null      int64
 4   price        7 non-null      int64
dtypes: int64(3), str(2)
memory usage: 412.0 bytes

## Describe()

In [27]:
df.describe()

               HP  Weight (KG)        price
count    7.000000     7.000000     7.000000
mean   113.714286  1244.571429   427.714286
std     99.966185   522.948008   872.248572
min     48.000000   850.000000    33.000000
25%     64.000000   975.000000    53.000000
50%     87.000000  1025.000000   105.000000
75%     99.000000  1283.500000   175.000000
max    335.000000  2320.000000  2400.000000

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

  <h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">💾 مصرف حافظه</h3>
  <p style="margin:0 0 12px; font-size:14px; color:#78828C;">Method است و باید با پرانتز فراخوانی شود</p>

  <p style="margin:0 0 14px; text-align:justify;">
    <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">memory_usage()</code> مصرف حافظه‌ی هر ستون را جداگانه (برحسب بایت) نشان می‌دهد؛ همان عددی که info() به‌صورت جمع‌شده در انتهای خروجی خود گزارش می‌کند. نکته‌ی مهم اینجاست: به‌طور پیش‌فرض، برای ستون‌های نوع object (مثل رشته‌ها) فقط اندازه‌ی اشاره‌گر شمرده می‌شود، نه اندازه‌ی واقعی محتوای رشته. برای گزارش دقیق، باید از پارامتر <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">deep=True</code> استفاده کرد.
  </p>
  <p style="margin:0 0 4px; text-align:justify;">
    یک بار <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">memory_usage()</code> را به‌صورت پیش‌فرض و یک بار با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:15px;">deep=True</code> اجرا کنید و تفاوت عدد گزارش‌شده برای یک ستون رشته‌ای را بررسی کنید.
  </p>
  <!-- کد را خودت بنویس -->

</div>